name: Deploy OCI VM with Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Set up OCI Private Key
      run: |
        mkdir -p ~/.oci
        echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
        ls -l ~/.oci/oci_api_key.pem

    - name: Terraform Init
      run: | 
        cd Bastion-host
        terraform init

    - name: Terraform Apply
      run: | 
        cd Bastion-host 
        terraform apply -auto-approve
      env:
        TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
        TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
        TF_VAR_fingerprint: ${{ secrets.OCI_KEY_FINGERPRINT }}
        TF_VAR_private_key_path: ~/.oci/oci_api_key.pem
        TF_VAR_region: ${{ secrets.OCI_REGION }}
        TF_VAR_compartment_id: ${{ secrets.OCI_COMPARTMENT_ID }}
        TF_VAR_availability_domain: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
        TF_VAR_subnet_id: ${{ secrets.OCI_SUBNET_ID }}
        TF_VAR_image_id: ${{ secrets.OCI_IMAGE_ID }}
        TF_VAR_ssh_public_key: "${{ secrets.OCI_SSH_PUBLIC_KEY }}"  # Pass public key content directly
